### ISSUE TITLE
Can't bind to 'value' since it isn't a known property of 'ay-treeTable'.

### ISSUE THREAD

**Issue by harishshan** [ddvkid/ng-treetable#10]
Can't bind to 'value' since it isn't a known property of 'ay-treeTable'.
1. If 'ay-treeTable' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'ay-treeTable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ay-treeTable [ERROR ->][value]="data">
    <ay-column field="name" header="Name"></ay-column>
    <ay-column field="gender"): PnmtreetableComponent@0:14
'ay-column' is not a known element:
1. If 'ay-column' is an Angular component, then verify that it is part of this module.
2. If 'ay-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<ay-treeTable [value]="data">
    [ERROR ->]<ay-column field="name" header="Name"></ay-column>
    <ay-column field="gender" header="Gender"></a"): PnmtreetableComponent@1:4
'ay-column' is not a known element:
1. If 'ay-column' is an Angular component, then verify that it is part of this module.
2. If 'ay-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<ay-treeTable [value]="data">
    <ay-column field="name" header="Name"></ay-column>
    [ERROR ->]<ay-column field="gender" header="Gender"></ay-column>
</ay-treeTable>"): PnmtreetableComponent@2:4
'ay-treeTable' is not a known element:
1. If 'ay-treeTable' is an Angular component, then verify that it is part of this module.
2. If 'ay-treeTable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ay-treeTable [value]="data">
    <ay-column field="name" header="Name"></ay-column>
    <ay-column"): PnmtreetableComponent@0:0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'ay-treeTable'.
1. If 'ay-treeTable' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'ay-treeTable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("<ay-treeTable [ERROR ->][value]="data">
    <ay-column field="name" header="Name"></ay-column>
    <ay-column field="gender"): PnmtreetableComponent@0:14
'ay-column' is not a known element:
1. If 'ay-column' is an Angular component, then verify that it is part of this module.
2. If 'ay-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<ay-treeTable [value]="data">
    [ERROR ->]<ay-column field="name" header="Name"></ay-column>
    <ay-column field="gender" header="Gender"></a"): PnmtreetableComponent@1:4
'ay-column' is not a known element:
1. If 'ay-column' is an Angular component, then verify that it is part of this module.
2. If 'ay-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("<ay-treeTable [value]="data">
    <ay-column field="name" header="Name"></ay-column>
    [ERROR ->]<ay-column field="gender" header="Gender"></ay-column>
</ay-treeTable>"): PnmtreetableComponent@2:4
'ay-treeTable' is not a known element:
1. If 'ay-treeTable' is an Angular component, then verify that it is part of this module.
2. If 'ay-treeTable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ay-treeTable [value]="data">
    <ay-column field="name" header="Name"></ay-column>
    <ay-column"): PnmtreetableComponent@0:0
    at SyntaxError.ZoneAwareError (http://localhost:3000/node_modules/zone.js/dist/zone.js:992:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1592:20)
    at new SyntaxError (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at TemplateParser.parse (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:11435:23)
    at JitCompiler._compileTemplate (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27548:72)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27431:66)
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27431:23)
    at createResult (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27313:23)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:334:26)
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:126:43)
    at http://localhost:3000/node_modules/zone.js/dist/zone.js:713:57
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:367:31)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:166:47)
    at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:546:35)

**Comment by ddvkid** [comment]
Hi, please make sure you have imported TreeTableModule successfully.

**Comment by harishshan** [comment]
Thanks, Once I am imported TreeTableModule it is working fine
