### ISSUE TITLE
Hide Columns

### ISSUE THREAD

**Issue by ElenaSeLE** [ddvkid/ng-treetable#14]
Hi!!

I like a lot this component. I have a dude, 
Would I be able to hide a single column?
I have to hide three columns when users colapse a Node. I watch on documentation onNodeCollapse event but I don't know how hide a column.

Thank you in advance!!
Regards!

Elena.

**Comment by ddvkid** [comment]
Hi Elena,
I'm glad you like my work, and thanks for supporting.
But I'm not very clear about your requirement, do you want to hide columns when all rows are collapsed or just one row collapsed?
A little tip for you, the treetable component will be dynamically setting a property 'expanded: boolean' to your raw data (nodes), so you can programmatically hide any columns by binding this property in your template.

**Comment by ElenaSeLE** [comment]
Hi! 
Finally I could hide some columns with your help, great!! I only create a event what modify a variable and this variable was linked to a class hidden the "ay-column" element.
But I have another problem. I need launch a method to download some information about the children row  (level 2) when a cell is clicked. 
I try to use onNodeSelect with selectionMode but it is always appearing "undefined" on "onRowClick" tables's method. How I could  modify this property and send the row/information about node children?

On the other hand, If I change the selectionMode value on console I get launch my even handle method but I can't get the row information to know if it was a leaf or what column it is, How I can obtain this information on the onNodeSelect handle method?

Thanks in advance! :)

**Comment by ElenaSeLE** [comment]
By the way,  I'm sorry for my English I'm a Spanish girl :(

**Comment by ddvkid** [comment]
Hi Elena,
I couldn't reproduce your issue, onNodeSelect works perfectly for me.
```
<ay-treeTable [value]="nodes.data" [globalFilter]="gb" selectionMode="single" (onNodeSelect)="nodeSelect($event)">
        <ay-column field="name" header="Name">
          <ng-template let-col let-node="rowData" pTemplate="body">
              <span>{{node.data[col.field]}}</span>
          </ng-template>
        </ay-column>
        
        <ay-column field="size" header="Size"></ay-column>
        <ay-column field="type" header="Type"></ay-column>
    </ay-treeTable>
```

Can you parse your code?
