### ISSUE TITLE
Demo not rendering

### ISSUE THREAD

**Issue by hugadams** [ddvkid/ng-treetable#17]
Hi,

My colleagues and I have been trying to use this library, but when we create a fresh ng-cli project and add ng-treetable as a dependency, it seems like stylesheets are missing.  You can see below the output of a table that I ripped directly from the demo folder of this project.

![image](https://user-images.githubusercontent.com/1972276/35000718-1bca640a-fab3-11e7-8f13-ee645b4269a2.png)

I'm using `ng-treetable v1.2.3` and seeing no errors in google chrome console.  However, there are no styles inherited in the project.  I suppose this means that ng-treetable directives are being understood, but not styled correctly?

![image](https://user-images.githubusercontent.com/1972276/35002034-50b8ad4a-fab6-11e7-9bef-70d54eb11974.png)

To add ng-treetable to a project, we simply add it to package.json, right?  All styling and so forth should just work out-of-the-box, right?

Thanks for putting this component together!

PS, can put my minimum working example/attempt onto github it that would help.

**Comment by ddvkid** [comment]
Please check [index.html](https://github.com/ddvkid/ng-treetable/blob/master/src/demo/index.html) and make sure you have put all these stylesheets in your angular-cli.json 
As a component, it's normally not a good idea to include the styling, because what it uses are some common css like bootstrap.css, it would double the bundle size if you already have it in your main project.

**Comment by RaviGprec** [comment]
Hi,
I like your package a lot. In fact you are saying our work a lot. 
Actually I'm also facing the same issue. I'm not getting tree structure. 
 
![image](https://user-images.githubusercontent.com/35065303/35098284-6740c2ca-fc08-11e7-8756-4799ba4ca650.png)
HTML template:
`<input #gb type="text" pInputText size="50" placeholder="Global Search">
  <ay-treeTable [value]="nodes.data" [globalFilter]="gb">
      <ay-column field="name" header="Name">
        <ng-template let-col let-node="rowData" pTemplate="body">
            <span>{{node.data[col.field]}}</span>
        </ng-template>
      </ay-column>      
      <ay-column field="size" header="Size"></ay-column>
      <ay-column field="type" header="Type"></ay-column>
  </ay-treeTable>`

**# The value for "nodes" is:**
`nodes = {
    "data":
        [
          {
            "data":{
              "name":"Documents",
              "size":"75kb",
              "type":"Folder"
            },
            "expanded":true,
            "children":[
              {
                "data":{
                  "name":"Work",
                  "size":"55kb",
                  "type":"Folder"
                },
                "children":[
                  {
                    "data":{
                      "name":"Expenses.doc",
                      "size":"30kb",
                      "type":"Document"
                    }
                  },
                  {
                    "data":{
                      "name":"Resume.doc",
                      "size":"25kb",
                      "type":"Resume"
                    }
                  }
                ]
              },
              {
                "data":{
                  "name":"Home",
                  "size":"20kb",
                  "type":"Folder"
                },
               
                
                "children":[
                  {
                    "data":{
                      "name":"Invoices",
                      "size":"20kb",
                      "type":"Text"
                    }
                  }
                ]
              }
            ]
          },
          {
            "data":{
              "name":"Pictures",
              "size":"150kb",
              "type":"Folder"
            },
            "expanded":true,
            "leaf":true,
            "children":[
              {
                "data":{
                  "name":"barcelona.jpg",
                  "size":"90kb",
                  "type":"Picture"
                }
              },
              {
                "data":{
                  "name":"primeui.png",
                  "size":"30kb",
                  "type":"Picture"
                }
              },
              {
                "data":{
                  "name":"optimus.jpg",
                  "size":"30kb",
                  "type":"Picture"
                }
              }
            ]
          }
        ]
      
  };`
It seems like there is something problem with CSS.
@hugadams : Have you resolved this problem? If so, please help me.

Thanks in Advance.

Regards,
Ravi Kumar

**Comment by ddvkid** [comment]
Hi @RaviGprec,
I'm glad my work helps you, as I mentioned earlier, there is no css in this library, this is by design.
You need to import whatever css framework you will use in your project, like bootstrap.
It is against library design to have explicit styling because whatever UI library you use, the styling should be consistent with your main app. 
Please see [index.html](https://github.com/ddvkid/ng-treetable/blob/master/src/demo/index.html), and try to import these styles in your project.

**Comment by RaviGprec** [comment]
Hi @ddvkid ,

Thanks for the reply!!. 
What I did is that: **I just copied all the four files from your project (./assets/styles/*). And pasted into my angular project. It is working well**.

Here my question is : **# Will there be any licence issues if do copy paste from your project?**
If so, suggest me correct way of using this css files.

Thanks in advance!!

Regards,
Ravi Kumar

**Comment by intellioption** [comment]
By the way, how can I have different width for each column? has anyone done that yet? Please let me know.
