### ISSUE TITLE
Can i use this ng-treetable if i dont use primeng?  

### ISSUE THREAD

**Issue by lefthand250** [ddvkid/ng-treetable#18]
hi ,
Can i use this ng-treetable if i dont use primeng?

**Comment by RaviGprec** [comment]
right now I'm using ng-treetable without primeng

**Comment by ddvkid** [comment]
Hi @lefthand250 
You don't need primeng for this component

**Comment by lefthand250** [comment]
Thanks for your reply
I find css is not working.
This is my html and data:
<ay-treeTable [value]="data">
  <ay-column field="name" header="Name"></ay-column>
  <ay-column field="gender" header="Gender"></ay-column>
</ay-treeTable>

{
    "data":
    [  
        {  
            "data":{  
                "name":"Andrew",
                "gender":"Male"
            },
            "children":[
                {  
                    "data":{  
                        "name":"Andrewson",
                        "gender":"Male"
                    },
                    "children":[  
                        {  
                            "data":{  
                                "name":"Eric",
                                "gender":"Male"
                            }
                        }                       
                    ]
                }
            ]
        }
    ]
}

**Comment by lefthand250** [comment]
<ay-treeTable [value]="data">
  <ay-column field="name" header="Name"></ay-column>
  <ay-column field="gender" header="Gender"></ay-column>
</ay-treeTable>

**Comment by lefthand250** [comment]
<ay-treeTable [value]="data"><ay-column field="name" header="Name"></ay-column> <ay-column field="gender" header="Gender"></ay-column></ay-treeTable>

**Comment by lefthand250** [comment]
`<ay-treeTable [value]="data">
  <ay-column field="name" header="Name"></ay-column>
  <ay-column field="gender" header="Gender"></ay-column>
</ay-treeTable>`
