### ISSUE TITLE
Does this package provide drag and drop functionality?

### ISSUE THREAD

**Issue by RaviGprec** [ddvkid/ng-treetable#19]
Hi @ddvkid ,

You are doing great job by putting your package in npm as an open source.

I'm using your package but I need extra functionality like drag drop.
Along with the drag and drop , I need "copy functionality when we drag and drop the nodes instead of move".

It would be great if your package has this kind of functionality as well. Not only me, many people also looking for this kind of requirement but unfortunately I didn't find any package that gives treeatble along with drag and drop fucntionality

Thanks in Advance,

Regards,
Ravi Kumar

**Comment by ddvkid** [comment]
#16 answered
