### ISSUE TITLE
How to set pagination?

### ISSUE THREAD

**Issue by wsjung0516** [ddvkid/ng-treetable#2]
1. After setting rows, pagination options as sample in the homepage. 
As expend the tree items, there is not any page separation,  the bottom line for page display is remained, displaying page no. 1.    
2. Even thought window size is set, the page expend continuously over the window size, whenever expend the tree items.

**Comment by ddvkid** [comment]
Hi wsjung, the pagination is only for the main page at the moment, I will add this feature in the next release.

**Comment by wsjung0516** [comment]
What's the meaning 'main page' ?
Following is my setting.
____________
  <input #gb type="text" pInputText size="50" placeholder="Input Search Text">
  <ay-treeTable [value]="userinfos" selectionMode="single" [(selection)]="selectedFiles"
                (onNodeSelect)="nodeSelect($event)"  [globalFilter]="gb" 
                rows="10" paginator="true" totalRecords = "10"
                >
    <ay-column field="text" header="구분"></ay-column>
    <ay-column field="userNm" header="사용자명"></ay-column>
    <ay-column field="userId" header="로그인ID"></ay-column>
    <ay-column field="rankNm" header="직급"></ay-column>
    <ay-column field="positionNm" header="직책"></ay-column>
    <ay-column field="userEmail" header="E-Mail"></ay-column>
    <ay-column field="userHpNo" header="전화번호"></ay-column>
    <ay-column field="deptNm" header="부서명"></ay-column>
  </ay-treeTable>
 ____________

**Comment by wsjung0516** [comment]
And the following is the another issue, When I try to execute your program the error message as...
The other day, You mailed to me some solution, but it didn't work.. 
-------------------
E:\Angular2\0421treetable\ng-treetable>ng serve
Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (E:\Angular2\0421treetable\ng-treetable\node_modules\@angular\cli\tasks\serve.js:22:63)
    at check_port_1.checkPort.then.port (E:\Angular2\0421treetable\ng-treetable\node_modules\@angular\cli\commands\serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ddvkid** [comment]
You are missing [], please try
`[rows]="10" [paginator]="true" [totalRecords] = "10"`

**Comment by ddvkid** [comment]
To run examples , you need to run `ng serve` under example directory.
use cd example before ng serve.

**Comment by wsjung0516** [comment]
As I attached pictures, 
Even though I set as you recommend, 
When I expend the tree, then the tree expand continuously over the page setting without separation pages.  

![ng-treetable1](https://cloud.githubusercontent.com/assets/10136862/25364288/45eddea8-299c-11e7-846a-98e18ad9bd47.png)
![ng-treetable2](https://cloud.githubusercontent.com/assets/10136862/25364292/4b2c3360-299c-11e7-8195-e26b3848d345.png)
![ng-treetable3](https://cloud.githubusercontent.com/assets/10136862/25364295/4f654a84-299c-11e7-9eed-82723c9f4d28.png)

**Comment by wsjung0516** [comment]
In the example program, 
When I tried to running at the example directory, following is the result of 'ng serve'
-------------------
Failed to compile.

Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in E:/Angular2/0425treetable/ng-treetable/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in E:/Angular2/0425treetable/ng-treetable/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in E:/Angular2/0425treetable/ng-treetable/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in E:/Angular2/0425treetable/ng-treetable/node_modules/@angular/core/index.d.ts, resolving symbol TreeTableModule in E:/Angular2/0425treetable/ng-treetable/src/treetable.ts, resolving symbol TreeTableModule in E:/Angular2/0425treetable/ng-treetable/src/treetable.ts

**Comment by ddvkid** [comment]
Sorry I couldn't fully understand your issue, but expend tree shouldn't change pagination anyway, the pagination only effect the main level.
In your case, there is only one item in the main level, this means no matter how many sub items you expanded, the pagination will remain 1.

**Comment by wsjung0516** [comment]
Now I understand, What you mean, only top level is effected . 
First time, when I saw you program, I wondered how you can separate the page keeping expend the tree. Now I suggest you, as the other solution like a jEasyUI, which has not pagination function but has vertical scrollbar instead.
