### ISSUE TITLE
How to adjust column size in the table?

### ISSUE THREAD

**Issue by RaviGprec** [ddvkid/ng-treetable#20]
Hi @ddvkid ,
Good day!!
My scenario is:
![image](https://user-images.githubusercontent.com/35065303/35324264-15f636a6-00a5-11e8-81e0-7e4a3552847c.png)
In the above table, name is not coming completely. how to make the size increaseable or decreasable ?

Thanks in advance!!

Have the good rest of the day!!

Regards,
Ravi Kumar

**Comment by syeddsherazi** [comment]
Facing similar issue

**Comment by RaviGprec** [comment]
Hi @syeddsherazi , Please let me know when you get the solution!!

**Comment by ddvkid** [comment]
Thanks for your inputs, I will add this feature soon. The idea is adding a "table-layout: auto" styling to <table> tag.
But currently we are missing a style (maybe call it tableStyle) property in table tag.

**Comment by RaviGprec** [comment]
thank you!! @ddvkid .

Let me us know when you are done with adding this feature.

Have a have good rest of the day!!

**Comment by ddvkid** [comment]
Hi @RaviGprec @syeddsherazi 
Two new properties have been added in the new version, tableStyle and tableStyleClass.
In your case, what you need to do is adding [tableStyle] like the following code:
```
<ay-treeTable [tableStyle]="{'table-layout': 'auto'}"></ay-treeTable>
```

**Comment by RaviGprec** [comment]
Hi @ddvkid ,

Thanks for the update. I'm facing below error after updating ng-treetable package.


> ERROR in Metadata version mismatch for module C:/Users/Administrator/Desktop/RAVIKUMAR/AVCDProject/VDApp/VDApp/node_modules/ng-treetable/ng-treetable.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/Administrator/Desktop/RAVIKUMAR/AVCDProject/VDApp/VDApp/src/app/app.module.ts, resolving symbol AppModule in C:/Users/Administrator/Desktop/RAVIKUMAR/AVCDProject/VDApp/VDApp/src/app/app.module.ts
> webpack: Failed to compile.

Could you tell me how to fix this issue?

Regards,
Ravi Kumar
