### ISSUE TITLE
sortable and href function

### ISSUE THREAD

**Issue by JianHe007** [ddvkid/ng-treetable#21]
Hi, your source code has really helped me.
And I have still have two questions, would you like to give me hints?
1, does this can add sorting column function?
2, how can I set hyper link to every node?  I want to click the row to jump to another page.
3, does it support mouse hover event?

**Comment by ddvkid** [comment]
Hi JianHe007,
I'm glad my work helps you! Here are the answers to your questions:
1. Unfortunately the current branch does not support column sorting, it might be added soon.
2. You can set selection properties in your template like this:
```
     <ay-treeTable [value]="nodes.data" [globalFilter]="gb"
                  selectionMode="single" [(selection)]="selectedRows"
                  (onNodeSelect)="nodeSelect($event)">
      <ay-column field="name" header="Name">
        <ng-template let-col let-node="rowData" pTemplate="body">
          <span>{{node.data[col.field]}}</span>
        </ng-template>
      </ay-column>
      <ay-column field="size" header="Size"></ay-column>
      <ay-column field="type" header="Type"></ay-column>
    </ay-treeTable>
```
3. You can use whatever event you want in the <ng-template> tag.
```
<ay-column field="name" header="Name">
        <ng-template let-col let-node="rowData" pTemplate="body">
          <span (mouseUp)="fn($event)">{{node.data[col.field]}}</span>
        </ng-template>
      </ay-column>
```

**Comment by JianHe007** [comment]
Hi ddvkid,
thanks for your kindness. It does work in No.2.
In No.3, I tried the "span (mouseUp)" ,it was not work. the "span (mouseover)" is OK.
Thank you again!
