### ISSUE TITLE
ng-treetable 1.3.3 update problem

### ISSUE THREAD

**Issue by RaviGprec** [ddvkid/ng-treetable#24]
Recently I tried updating ng-treetable package to 1.3.3. 

After updating ng-treetable to 1.3.3.

I tried lunching my application.

But I'm facing the following error:

**ERROR in Metadata version mismatch for module C:/Users/Administrator/Desktop/RAVIKUMAR/AVCDProject/VDApp/VDApp/node_modules/ng-treetable/ng-treetable.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/Administrator/Desktop/RAVIKUMAR/AVCDProject/VDApp/VDApp/src/app/app.module.ts, resolving symbol AppModule in C:/Users/Administrator/Desktop/RAVIKUMAR/AVCDProject/VDApp/VDApp/src/app/app.module.ts
webpack: Failed to compile.**

**Comment by andrew-yangy** [comment]
Provide your package.json plz

**Comment by RaviGprec** [comment]
`{
  "name": "vdapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.4",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular-bootstrap-grid-tree": "^0.4.0",
    "angular-tree-component": "^4.1.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.5.3",
    "ng-treetable": "^1.3.3",
    "primeng": "^5.2.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.99",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
`

**Comment by andrew-yangy** [comment]
Make sure your angular modules in same version, animations

**Comment by RaviGprec** [comment]
Sorry @ddvkid ,

I'm not getting what you are trying to say.

Could you please tell me in detailed way.

Where I'm doing wrong here.

Thanks& Regards,
Ravi Kumar

**Comment by andrew-yangy** [comment]
"@angular/animations": "^5.2.4"  "@angular/common": "^4.0.0"
you are using different version of angular

**Comment by RaviGprec** [comment]
Even I did that but no use. Still the problem is same

**Comment by RaviGprec** [comment]
![image](https://user-images.githubusercontent.com/35065303/36085285-9cd92eb6-0f79-11e8-900d-0eed4092561f.png)

**Comment by andrew-yangy** [comment]
Can you try to upgrade to angular 5, I just release I was using ng5 compiler to compile the new version, so it only supports 5 now.

**Comment by RaviGprec** [comment]
The problem is with ng-treetable only. 

If I downgrade ng-treetable version to 1.2.3 then it is  working. But for ng-treetable version 1.3.3 the problem is same.

![image](https://user-images.githubusercontent.com/35065303/36085661-2415ad76-0f7c-11e8-9a45-1f45e6b3abe3.png)

**Comment by andrew-yangy** [comment]
Yes,like I said, plz upgrade your angular to 5

**Comment by RaviGprec** [comment]
I upgraded it to Angular5 . But somehow my project was totally corrupted. I'm getting so many errors because of upgradation.

**Comment by RaviGprec** [comment]
below is the screenshot of the error when I try "ng serve" after migration of Angular 2 to 5.
![image](https://user-images.githubusercontent.com/35065303/36255815-7659dae2-1276-11e8-937c-d212b3fe5f54.png)

And **# my package.js file:**
`{
  "name": "vdapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.3.1",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular-tree-component": "^4.1.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.5.3",
    "ng-treetable": "^1.3.3",
    "primeng": "^5.0.2",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.96",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.4.0"
  }
}
`

**Comment by andrew-yangy** [comment]
ur complie cli is still 4

**Comment by RaviGprec** [comment]
Thanks for that!! I've updated it and is being compiled. But the problem is with Angular 5.

![image](https://user-images.githubusercontent.com/35065303/36294780-d3943254-1297-11e8-9b51-1c73fd9b34a6.png)

If I'm not wrong, this is due to migration from angular4 to 5. 
# **ngOutletContext (deprecated) to ngTemplateOutletContext**
