### ISSUE TITLE
ngOutletContext (deprecated) to ngTemplateOutletContext

### ISSUE THREAD

**Issue by RaviGprec** [ddvkid/ng-treetable#25]
Recently I updated my project from angular 4 to 5. and ng-treetable to 1.3.3 

But I'm having trouble with angular 5 with the following error:
![image](https://user-images.githubusercontent.com/35065303/36408870-eac508cc-15bc-11e8-9dd3-097b77f84aa6.png)

My Package.json file:
`{
  "name": "vdapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^0.3.1",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular-tree-component": "^4.1.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.5.3",
    "ng-treetable": "^1.3.3",
    "primeng": "^5.0.2",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.96",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.4.0"
  }
}
`

Kindly look into it.

**Comment by RaviGprec** [comment]
Hi @ddvkid
Are you working on it?

Regards,
Ravi Kumar

**Comment by andrew-yangy** [comment]
any angular upgrade issues, plz submit to Angular repo
