### ISSUE TITLE
ng-treetable table border and table look not shown 

### ISSUE THREAD

**Issue by goel-sunny** [ddvkid/ng-treetable#26]
my data is shown in tree list format but its surrounded table is not shown , i try all of this but table look not shown only data is shown . can anybody suggest me the reason of  this problem

**Comment by goel-sunny** [comment]
add the addition css file @refer primeNG for that table border and look

**Comment by syedirfan7** [comment]
@goel-sunny did you got it fixed ? i am getting same issue with 1.2.3 version for angular 4 
can you please share the files if you have ?
