### ISSUE TITLE
problem while changing an input field (create using ng-template ) in checkbox selection feature.

### ISSUE THREAD

**Issue by goel-sunny** [ddvkid/ng-treetable#27]
while i am selecting the a row  by clicking the checkbox , and after selection when i am going to change the input field column of that row , at the time of clicking of that input field the entire row goes dis selecting, so is their is no combination possible of checkbox selection and input or button features using ng-template directive in angular2+.

**Comment by andrew-yangy** [comment]
Sorry, I am not very clear about your issue, are you saying that you have a editable field in row? Can you provide a online demo for this?

**Comment by goel-sunny** [comment]
yes my mean is editable field in the row , so when i click on the field to edit something or update something my checkbox selected row got diselected . so tell me is their is any way to come out of this problem.

**Comment by andrew-yangy** [comment]
It sounds like a event bubbling issue, try to use event.stopPropagation() to avoid this.

**Comment by goel-sunny** [comment]
but how to invoke that in this case.

**Comment by goel-sunny** [comment]
` <ay-treeTable [value]="data"  (selected)="checkbox" [style]="{'width':'100%'}">
      <ay-column field="name"  [style]="{'width':'40%'}"> </ay-column>
      <ay-column field="abc" [style]="{'width':'10%'}">
        <ng-template let-col let-node="rowData" pTemplate="header">
          ABC
        </ng-template>
        <ng-template let-col let-node="rowData" pTemplate="body">
          <div>
            <input [(ngModel)]="node.data.abc" type="text"  style="width:100%">
          </div>
        </ng-template>
      </ay-column>
</ay-treeTable>
 `


can you tell me in this how i can do your conclusion

**Comment by andrew-yangy** [comment]
https://stackoverflow.com/questions/35274028/stop-mouse-event-propagation-in-angular
