### ISSUE TITLE
search filter is not working ?

### ISSUE THREAD

**Issue by goel-sunny** [ddvkid/ng-treetable#28]
<input #gb type="text" pInputText size="50" placeholder="Global Filter">
<ay-treeTable [value]="data" [globalFilter]="gb" [rows]="10" [paginator]="true" [pageLinks]="3" [rowsPerPageOptions]="[5,10,20]">
    <ay-column field="name" header="Name"></ay-column>
    <ay-column field="gender" header="Gender"></ay-column>
</ay-treeTable>

i have try this , in that when i type something in search nothing happen , treelist remain as in initial state , dont know what do to , is their is anything we need to add in this.

**Comment by andrew-yangy** [comment]
I'm not able to reproduce this issue without further information.
Can you try this example? https://github.com/ddvkid/ng-treetable/blob/master/src/demo/app/app.component.ts

**Comment by goel-sunny** [comment]
basically when i am entering something in the search input , it is not filtering anything but when i click on the tree table item (after writing what we want to search in search box) then it display me the list. i dont know why this is happening.

**Comment by andrew-yangy** [comment]
can you try the example?

**Comment by goel-sunny** [comment]
yes this sample runs fine but can you tell me what is going wrong in my case.

**Comment by andrew-yangy** [comment]
Can you provide more information?

**Comment by goel-sunny** [comment]
i am using bootstrap 4  , angular 5 , and no JQuery  .  in this when i write something in search box then nothing happen but ater writing when i click on that tree data it showes me list  ,

**Comment by goel-sunny** [comment]
is this because any other event stop this event from happening or something else .
