### ISSUE TITLE
how to disable particular tree node checkbox 

### ISSUE THREAD

**Issue by AnneWQ** [ddvkid/ng-treetable#8]
I use treeTable with checkbox, but i want to disable all checkbox of child node.
How can I achieve this?
If do this as official doc says: 'Selection of a particular node can be disabled by setting the selectable property of the node to false.', how to do this in practice, in html or in typescript code?

thank you very much

**Comment by ddvkid** [comment]
Hi Anne, I'm assuming you are using the build-in checkbox mode, which unfortunately does not support disable particular node atm.
However, you can implement something like this:
```
<ay-column field="name" header="Name">
    <template let-col let-node="rowData" pTemplate="body">
        <input type="checkbox" [disabled]="node.parent">
    </template>
</ay-column>
```

**Comment by AnneWQ** [comment]
Hi, thx for replying,
I just figure out how to disable build-in checkbox:

Assume my tree data are follows:
`
data=[
    {
        data:{name:'aa'},
        children:[
            {data:{name:'ab'}}
        ]
    }
]
`

I want to set my children node undelectable, do like this:

`
data[0].children[0].selectable=false
`

Then, children node cannot be selected in UI (it works for my project), but the style of the checkbox does not change. I have to add a styleClass to hide it (of course, you can set other CSS styles).

**Comment by ddvkid** [comment]
Glad you have worked it out:)
Of course you can reset the data model and add a new property 'selectable' to each node, but It would potentially slow down your app if the data amount is huge.
My advise did not require any changes on data model, thus it could be much faster.
