### ISSUE TITLE
any property similarly with 'filterMatchMode' in DataTable of primeNG?

### ISSUE THREAD

**Issue by AnneWQ** [ddvkid/ng-treetable#9]
hi, 

can I filter the treeTable with particular few columns?

all best
anne

**Comment by ddvkid** [comment]
Only column with <ay-column header></ay-column> will be filtered by the global filter, use 
``<ay-column><template></template></ay-column>`` instead if you don't want this column to be filtered.

**Comment by AnneWQ** [comment]
great
thank you!
